- name: Deploy lamp stack application
  yum:
    name:
      - libselinux-python
      - libsemanage-python
      - firewalld
    state: installed

    
- name: Install MariaDB package
  yum:
    name:
    - mariadb-server
    - MySQL-python
    state: installed

- name: Create Mysql configuration file
  copy: src=files/my.cnf dest=/etc/my.cnf

- name: Retart MariaDB Service
  service: name=mariadb state=restarted enabled=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes

- name: Create Application Database
  mysql_db: 
    login_user: root
    login_password: 123456    
    name: "{{ dbname }}"
    state: present
  tags: DB_Creation



- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL host='node2' state=present
  tags: DB_user_creation

- name: Move db-load-script to db host
  copy:
    src: files/db-load-script.sql
    dest: /tmp/db-load-script.sql

- name: Load Inventory Data
  shell: mysql -f < /tmp/db-load-script.sql
          

- name: Install httpd and php
  yum:
    name:
      - httpd
      - php
      - php-mysql
    state: present

- name: Install web role specific dependencies
  yum: name=git state=installed

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule for httpd
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes

- name: Set index.php as the default page
  tags: "Set index.php as the default page"
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'DirectoryIndex index.html'
    replace: 'DirectoryIndex index.php'

- name: http service state
  service: name=httpd state=started enabled=yes
  
- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/  force=yes

- name: Update remote server ip in index.php
  command: sed -i 's/172.20.1.101/192.168.56.101/g' /var/www/html/index.php
